version: "3.1"
services:
  jenkins:
    build: ../
    ports:
      - 8088:8080
      - 50000:50000
    volumes:
      - /vagrant/slave.jar:/var/jenkins_home/slave.jar
    networks:
      main:
networks:
  main:
